name: LeadEight
favicon: null
layout_spectrum: 0.016298879869282246
typography_spectrum: 0.4000205632764846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.017044755863025784
  saturation: 0.3716454526875168
  rhythmicContrast: 0.6491247660014778
purpose: []
