name: LeadEight
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#ffffff'
    - '#9f9f9f'
    - '#414141'
    - '#626262'
  brandStrength: 0.5
  lightness: 0.017044755863025784
  saturation: 0.3716454526875168
  rhythmicContrast: 0.6491247660014778
purpose: []
